const copy = {
  es: {
    navAbout:'Sobre mí',navServices:'Servicios',navProjects:'Proyectos',navProcess:'Proceso',navContact:'Contacto',
    eyebrow:'DESARROLLO INDEPENDIENTE · TORONTO / REMOTO',heroTitle:'Ideas complejas,<br><em>herramientas claras.</em>',heroLede:'Convierto ideas, procesos y necesidades complejas en aplicaciones, automatizaciones e integraciones prácticas.',heroCta:'Hablemos de tu idea <span>↗</span>',heroExplore:'Explorar proyectos ↓',aboutLabel:'SOBRE MÍ',aboutTitle:'Tecnología útil,<br><em>sin ruido.</em>',aboutCopy:'Soy Jairy Bordon, desarrollador independiente de software. Ayudo a convertir ideas y procesos complejos en herramientas digitales prácticas.',aboutCopy2:'Trabajo desde la conversación inicial hasta un alcance claro, un prototipo o una primera versión. Me interesa entender el problema antes de añadir complejidad.',servicesLabel:'QUÉ PUEDO CONSTRUIR',servicesTitle:'Del problema<br><em>al siguiente paso.</em>',service1Title:'Aplicaciones',service1Copy:'Aplicaciones web y software personalizado para necesidades concretas.',service2Title:'Automatización',service2Copy:'Flujos de trabajo más simples, menos tareas repetitivas.',service3Title:'Integraciones',service3Copy:'Sistemas y fuentes de datos que necesitan trabajar juntos.',service4Title:'Definición',service4Copy:'Descubrimiento, requisitos y prototipos antes de construir.',projectsLabel:'PROYECTOS',projectsTitle:'Trabajo propio,<br><em>aprendizajes reales.</em>',projectsIntro:'Una selección inicial de proyectos y exploraciones. Cada ficha conserva su estado real y sus límites.',projectPending:'Proyecto identificado por nombre; falta documentación suficiente para describir alcance y estado.',projectCategory:'Aplicación / sistema digital',tradingProject:'Herramienta relacionada con trading presentada como proyecto tecnológico, no como identidad financiera.',tradingCategory:'Software / trading',processLabel:'CÓMO TRABAJO',processTitle:'Primero entender.<br><em>Después construir.</em>',process1Title:'Conversación',process1Copy:'Qué quieres resolver, quién lo necesita y cómo funciona hoy.',process2Title:'Claridad',process2Copy:'Requisitos, límites y una primera versión posible.',process3Title:'Construcción',process3Copy:'Una solución proporcionada al problema real.',contactEyebrow:'¿TIENES UNA IDEA DIGITAL?',contactTitle:'Hagamos claro<br><em>el siguiente paso.</em>',contactCopy:'Cuéntame qué proceso, idea o sistema quieres mejorar. Podemos empezar con una conversación.',emailCta:'Escribir por email <span>↗</span>',callCta:'Llamar <span>↗</span>',footerRole:'Independent Software Developer'
  },
  en: {
    navAbout:'About',navServices:'Services',navProjects:'Projects',navProcess:'Process',navContact:'Contact',
    eyebrow:'INDEPENDENT DEVELOPMENT · TORONTO / REMOTE',heroTitle:'Complex ideas,<br><em>clearer tools.</em>',heroLede:'I turn complex ideas, workflows, and business needs into practical applications, automation, and integrations.',heroCta:'Let’s discuss your idea <span>↗</span>',heroExplore:'Explore projects ↓',aboutLabel:'ABOUT',aboutTitle:'Useful technology,<br><em>without the noise.</em>',aboutCopy:'I’m Jairy Bordon, an independent software developer. I help turn complex ideas and workflows into practical digital tools.',aboutCopy2:'I work from the first conversation to a clear scope, prototype, or first version. I believe in understanding the problem before adding complexity.',servicesLabel:'WHAT I BUILD',servicesTitle:'From the problem<br><em>to the next step.</em>',service1Title:'Applications',service1Copy:'Web applications and custom software for concrete needs.',service2Title:'Automation',service2Copy:'Simpler workflows with fewer repetitive tasks.',service3Title:'Integrations',service3Copy:'Systems and data sources that need to work together.',service4Title:'Definition',service4Copy:'Discovery, requirements, and prototypes before building.',projectsLabel:'PROJECTS',projectsTitle:'Personal work,<br><em>real learnings.</em>',projectsIntro:'An initial selection of projects and explorations. Each entry keeps its real status and limits.',projectPending:'Project identified by name; more documentation is needed to describe its scope and status.',projectCategory:'Application / digital system',tradingProject:'Trading-related tool presented as a technology project, not as a financial identity.',tradingCategory:'Software / trading',processLabel:'HOW I WORK',processTitle:'Understand first.<br><em>Then build.</em>',process1Title:'Conversation',process1Copy:'What needs solving, who needs it, and how it works today.',process2Title:'Clarity',process2Copy:'Requirements, boundaries, and a possible first version.',process3Title:'Build',process3Copy:'A solution proportionate to the real problem.',contactEyebrow:'HAVE A DIGITAL IDEA?',contactTitle:'Let’s make the<br><em>next step clear.</em>',contactCopy:'Tell me which workflow, idea, or system you want to improve. We can start with a conversation.',emailCta:'Write by email <span>↗</span>',callCta:'Call <span>↗</span>',footerRole:'Independent Software Developer'
  }
};
const setLanguage=(lang)=>{document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(copy[lang][key])el.innerHTML=copy[lang][key]});document.querySelectorAll('.language').forEach(el=>el.classList.toggle('active',el.dataset.lang===lang));try{localStorage.setItem('jb-lang',lang)}catch(_){}}
document.querySelectorAll('.language').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();setLanguage(el.dataset.lang)}));
const menu=document.querySelector('.menu-toggle');const mobile=document.querySelector('#mobile-nav');menu.addEventListener('click',()=>{const open=mobile.classList.toggle('open');menu.setAttribute('aria-expanded',open)});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobile.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
document.querySelector('#year').textContent=new Date().getFullYear();let savedLanguage='es';try{savedLanguage=localStorage.getItem('jb-lang')||'es'}catch(_){}setLanguage(savedLanguage);
